### ISSUE TITLE
Target

### ISSUE THREAD

**Issue by mldaq** [oliverfoster/adapt-graphicLink#1]
@oliverfoster - i've added this component to my course and tested it out in AT and is does not seem to be working properly for me. If I click the link it still opens in another window. I selected _self in teh component settings, but if I do an inspect it does not look like it is adding the target="_self" to the code.
<img width="714" alt="screen shot 2017-06-19 at 11 49 03 am" src="https://user-images.githubusercontent.com/15389177/27296147-53feed7e-54e5-11e7-83a1-ce205a49ba36.png">

**Comment by oliverfoster** [comment]
https://github.com/cgkineo/adapt-graphicLink/blob/master/js/adapt-graphicLink.js#L53 it doesn't use an `a` tag. I'll modify it to use backbone or window.location.href accordingly.

**Comment by oliverfoster** [comment]
hopefully the latest version should fix it
